language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
env:
  - COVERALLS_REPO_TOKEN=AyUFfhc2yproIdrm7vqeSRDdvy4MeCT1S 
script:
  - npm run lint
  - npm test
  - npm run coveralls
after_success: 'npm run coveralls'